### ISSUE TITLE
Expected output files from make_manifest and instructions for rendering in Unity

### ISSUE THREAD

**Issue by moldach** [ropensci/terrainr#42]
I'm wondering what the expected output is from the README example for Unity is?:

```
make_manifest(output_tiles$elevation, output_tiles$ortho)
```

> _Note: The instructions for Unity creates an `output_tiles` object using a `simulated_data` object which was never created in the README?_

```
with_progress( # When not specifying resolution, default is 1m pixels
  output_tiles <- get_tiles(simulated_data,
                            services = c("elevation", "ortho"))
)
```
> _therefore I used `output_tiles` from the beginning of the README:

```
library(terrainr)
library(sf)

# Optional way to display a progress bar while your tiles download:
library(progressr)
handlers("progress")
handlers(global = TRUE)

location_of_interest <- tmaptools::geocode_OSM("Hyampom California")$coords

location_of_interest <- data.frame(
  x = location_of_interest[["x"]],
  y = location_of_interest[["y"]]
)

location_of_interest <- st_as_sf(
  location_of_interest, 
  coords = c("x", "y"), 
  crs = 4326
)

location_of_interest <- set_bbox_side_length(location_of_interest, 8000)

output_tiles <- get_tiles(location_of_interest,
                          services = c("elevation", "ortho"),
                          resolution = 30 # pixel side length in meters
                          )
                          
merged_dem <- merge_rasters(output_tiles[["elevation"]], 
                            tempfile(fileext = ".tif"))
merged_ortho <- merge_rasters(output_tiles[["ortho"]], 
                              tempfile(fileext = ".tif"))

make_manifest(output_tiles$elevation,
              output_tiles$ortho)
```

I see the following in my working directory:

```
import_1_1.png
import_1_1.png.aux.xml
import_1_1.raw
import_terrain.cs
terrainr.manifest
```

Is this the expected output?

Next, how do we load these _tiles_ (which files specifically) into Unity and render a scene?

**Comment by mikemahoney218** [comment]
Hi @moldach ! Sorry for the delay, I've been on vacation.

Yes! That's exactly right. The documentation for importing those tiles into Unity can be found at:
https://docs.ropensci.org/terrainr/articles/unity_instructions.html

Let me know if that vignette makes sense!

**Comment by moldach** [comment]
Hi @mikemahoney218,

Hope you had a good vacation.

Thanks for creating that documentation, it made perfect sense.
The rest is all `Unity` specific I suppose (_easy_ ... <stares into the abyss of a complicated GUI> ... _right_).

Thanks again
