### ISSUE TITLE
Migrate off {raster}

### ISSUE THREAD

**Issue by mikemahoney218** [ropensci/terrainr#45]
The raster package will be deprecated in 2024, and it's time to start thinking about moving off of one of the core dependencies of the project.

The clear alternative is {terra}, given that it's by the same developer and has a similar API. However, I think it would be worthwhile to look into using {stars} for internal computation, so that the entire package (with its dependencies on units, sf, and stars) fits into one of the main silos of geocomputation. 

Functions accepting raster inputs should quietly cast to the new format before continuing. I don't think any function returns raster objects directly -- usually we return file paths to a raster -- but if so, changing this will require a major version update.

**Comment by mdsumner** [comment]
I don't think think raster will stop functioning, it will just stop being reliant on sp,rgdal and more on terra. 

You might also look at vapour for reading raster data from services, because gdal can do a lot of that without managing tiles etc   🙏
