### ISSUE TITLE
gdalwarp runs into system-level open file limits when merging many tiles

### ISSUE THREAD

**Issue by mikemahoney218** [ropensci/terrainr#49]
When attempting to use gdalwarp to merge many files, gdalwarp begins by opening a connection to each input file. On some systems (including Linux) this causes an error when there are more input files than may be opened by a single process at once (default 1024). This causes merging to fall over to merge_rasters_deprecated which appears to work often, but not always, as a replacement.

One potential fix is to use `gdalbuildvrt` to "combine" the tiles into a virtual raster, and then `gdalwarp` to transform that virtual raster to an on-disk file. I'm not sure about the implications of this for performance -- possibly we only do this when merging > 100 files?

**Comment by mdsumner** [comment]
ooh I've never seen this, did you resolve? I used to get this with equivalent of gdal_translate of 1000s of netcdfs in a multiband vrt

Ive never seen this with the warper but also I can't imagine calling it with 1000s of sources, probably never more than several so I might try.

**Comment by mikemahoney218** [comment]
Yeah, I wish I had the commit reference this issue (it's 64318f87208abb672d160b82bb3e3668b1c88eef ) but I fixed this as part of moving off gdalUtils. I didn't bother finding out the precise limitations, just have a kludge where if the first go with gdalwarp fails, fall  back to vrt -> warp (because that seems to handle a lot of edge cases).

**Comment by mdsumner** [comment]
ah! thanks - this is something I have to actually try out (when I take a break from gdal itself), it's very cool!  It seems like your new process does cut way better with gdal, that's good - there are things sf/stars and terra can't do (I've learned ...) but I don't think they affect your process here
