### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [ropensci/terrainr#57]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by mikemahoney218** [comment]
Thanks @rsbivand -- appreciate all the communication from you (and others!) as these packages are retired. Most of the work should be already done with this package. I'll send a new release to CRAN early next year -- I want to wait until after the winter break, to avoid having a broken release that I can't update.

**Comment by rsbivand** [comment]
Sounds like a sensible plan!

**Comment by mikemahoney218** [comment]
Thanks for flagging; the CRAN version has removed the rgdal dependency.
