### ISSUE TITLE
get_tiles hangs when National Map API non-responsive

### ISSUE THREAD

**Issue by fred-watson** [ropensci/terrainr#60]
Sometimes get_tiles hangs in an infinite loop trying for a correct API response to a request for an ortho image. Maybe 50% or more of the time it works fine. Maybe 50% or less of the time it hangs. With verbose=TRUE, I get an infinite sequence of messages "API call 2 attempt 1". When I ESC out, R itself sometimes hangs and I need to restart.

Looking near Line 220 of hit_api.R, I get the sense that "counter" is never incremented, so as long as the API is not behaving, the while loop never ends.

Suggestions / questions:
1. Short term. A graceful exit from the loop would be good i.e. counter=counter+1.
2. Any ideas why the API sometimes seems to be non-responsive?

Thanks!

**Comment by mikemahoney218** [comment]
Hey @fred-watson -- appreciate the issue. 

Second question first: the national map services have been a bit of a mess as of late. You can see their status at this link:
https://stats.uptimerobot.com/gxzRZFARLZ

The default ortho service is at this link:
https://stats.uptimerobot.com/gxzRZFARLZ/793055957

You _might_ have better luck setting `service = "USGSNAIPImagery"`, which has had a slightly better track record recently:
https://stats.uptimerobot.com/gxzRZFARLZ/793313548

But no promises; I'm not affiliated with USGS in any capacity so can't speak to why services have more or less uptime.

I've reached out to the team at USGS a few times, and every time have been told the team is aware and working on improving reliability; I wish I had more than that to share.

Thanks for catching that loop issue; I missed that entirely. Will fix in a minute.

**Comment by fred-watson** [comment]
Thanks @mikemahoney218 . Super-helpful. (Great package, by the way.)
