### ISSUE TITLE
show.legend()

### ISSUE THREAD

**Issue by dongyiyi** [ropensci/terrainr#69]
Thank you for developing this package! I tried to use the geom_spatial_rgb() function to plot the RGB plot with a raster object, which did great work, except for the legend. I run the code with `show.legend = Ture`, or modify the source code in the function. I always get the plot without the legend.

```r

ggplot() + geom_spatial_rgb(data = raster_object, aes(x = x, y = y, r = loc_scaled, g = for_scaled, b = rev_scaled))

```
Thanks!

**Comment by mikemahoney218** [comment]
Thanks for the issue! This is mostly intended; the normal use for this function is to include a "basemap" under other data, and so you don't want a legend for the base map (as the RGB values don't represent anything other than the desired RGB of the output image). I'm unfortunately not likely to add the ability to add legends to this function in this package; I unfortunately am not able to spare the time for that feature right now.

I _believe_ this is a relatively standard approach; it looks like tidyterra also doesn't produce legends for its RGB method:
https://dieghernan.github.io/tidyterra/reference/geom_spatraster_rgb.html

That said, check out geom_spatraster() from tidyterra for a more generic method for visualizing rasters that might be helpful:
https://dieghernan.github.io/tidyterra/reference/geom_spatraster.html

**Comment by dongyiyi** [comment]
Thank you for clarifying!
